Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -8,6 +8,12 @@ jobs:
 
     steps:
       - uses: actions/checkout@v2
+      
+      - name: Greeting
+        run: echo "Hello, world!"
 
+      - name: Simulate an error
+        run: echo "About to fail" ; exit 1
+      
       - name: Run a one-line script
         run: echo "Hello, world!"
